### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by jukent** [NCAR/jupyter-forward#2]
The first thing I noticed that would improve the documentation is having the motivation for jupyter-forward right at the beginning. Why do we want to port forward Jupyter Lab sessions back to our local machine? I haven't done this so I am not sure I have the best answer. What I've gathered from the conversations is that we want to be able to shut down our local machine without shutting down the server (but also make sure people know that the server is still running so they aren't spending $$$). I'm not super confident on how to connect everything. Is this the right idea @andersy005 ? Did you have other things in mind that you wanted to change about the documentation?

**Comment by mnlevy1981** [comment]
I think the biggest use case for this at NCAR is to mimic the behavior of Jupyter Hub when `cheyenne` is down for maintenance. If we still have access to `casper`, users can run `jupyter lab` themselves instead of relying on the hub, but it's a complicated process. From my point of view, the one-line motivation for this tool is to "simplify the process of running `jupyter lab` on a remote machine."

**Comment by mnlevy1981** [comment]
There are a few different answers to "why do we want to port forward Jupyter Lab sessions back to our local machine?"

1. If we are analyzing data on the super computer, we don't need a copy of it locally (and it might be large enough that copying it to our local machine is infeasible)
1. If we are analyzing data on the super computer, we can take advantage of the compute nodes via dask
1. Even if we limit ourselves to the head node, it likely has more memory and a better cpu than our local machine
